name: CI workflow
on: 
  push:
    branches: ["main", "test_workflow"]
  pull_request:
    branches: ["main", "test_workflow"]

defaults:
  run:
    working-directory: ./lab2/TDD

jobs: 
  build: 
    runs-on: ubuntu-latest
    container: python:3.9-slim

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tets with pytests
        run: pytest -v --tb=short --color=yes --cov=src --cov-report=term-missing
